### PR TITLE
[timeout] full implementation, 3d iteration

### PR DESCRIPTION
**Pull request by Wandalen**

### CODE REVIEW

**Comment by Wandalen** [comment]
Might fail because of grep

**Comment by Wandalen** [comment]
Ready @jgarzik

**Comment by jgarzik** [comment]
Also CI is succeeding, local tests with Ubuntu Linux 22.04 LTS are failing:
```
failures:

---- timeout::test_utility_error stdout ----
thread 'timeout::test_utility_error' panicked at process/tests/timeout/mod.rs:66:5:
assertion `left == right` failed
  left: "/usr/bin/sleep: invalid time interval 'invalid_value'\nTry '/usr/bin/sleep --help' for more information.\n"
 right: "/usr/bin/sleep: invalid time interval ‘invalid_value’\nTry '/usr/bin/sleep --help' for more information.\n"
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/std/src/panicking.rs:665:5
   1: core::panicking::panic_fmt
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:74:14
   2: core::panicking::assert_failed_inner
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:410:17
   3: core::panicking::assert_failed
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/panicking.rs:365:5
   4: process_tests::timeout::run_test
             at ./tests/timeout/mod.rs:66:5
   5: process_tests::timeout::timeout_test
             at ./tests/timeout/mod.rs:85:5
   6: process_tests::timeout::test_utility_error
             at ./tests/timeout/mod.rs:244:5
   7: process_tests::timeout::test_utility_error::{{closure}}
             at ./tests/timeout/mod.rs:237:24
   8: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
   9: core::ops::function::FnOnce::call_once
             at /rustc/eeb90cda1969383f56a2637cbd3037bdf598841c/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.


failures:
    timeout::test_utility_error

test result: FAILED. 38 passed; 1 failed; 3 ignored; 0 measured; 0 filtered out; finished in 10.29s

```

**Comment by Wandalen** [comment]
@jgarzik fixed

**Pull request merged**
