### PR TITLE
Histogram diff

### PR DESCRIPTION
**Pull request by gcanat**
#225 

Implements histogram diff. I had to change quite a bit how the diff is printed because I believe having to annotate each line of the files with `Change::{Unchanged, Deleted, Inserted}` etc was not optimal. We just need to know where the hunks start and end.

Todo:
---
- [x] fix `print_context()`
- [x] fix `print_edit_script()`
- [x] test more thoroughly the output of unified print and default print.
- [x] refactor `create_hunks_from_lcs()`
- [x] fix unit tests

Nice to have
---
- [ ] more code cleaning: for example, we probably dont need the `ChangeData` struct at all in the end.
- [ ] eventually add a fallback method for cases where histogram diff is known to under-perform (big repetitive files), eg Myers diff

### CODE REVIEW

**Comment by jgarzik** [comment]
Are any of the community crates sufficiently low-dep and worth using?  https://crates.io/crates/imara-diff or https://crates.io/crates/diff-match-patch-rs or https://crates.io/crates/diff ?

**Comment by gcanat** [comment]
Ah yes, I didn't think that was an option. But indeed imara-diff has just two dependencies: ahash and hashbrown. It is probably the fastest diff library out there.

**Comment by jgarzik** [comment]
> Ah yes, I didn't think that was an option. But indeed imara-diff has just two dependencies: ahash and hashbrown. It is probably the fastest diff library out there.

std-only is certainly the preference.

However, low-dep and no-dep algorithm crates that avoid our reinventing the wheel is OK as an exception.

We want to avoid "heavy" deps such as serde, nix, rustix, tokio etc.  (alas, still working on that...)

**Comment by gcanat** [comment]
Ok so the default diff, unified diff and edit_script are working fine. I think the implementation is quite performant. Just tested by cloning [helix](https://github.com/helix-editor/helix) in two different dirs, checking out for one of them to 22.08.1 and doing `target/release/diff -ru dir1 dir2 > helix.diff`. It produces a 67k lines diff file in 140ms.

I just need to finish updating `print_context()` and then we should have a decent mvp.

**Review by jgarzik — APPROVED** [review]
LGTM

**Comment by jgarzik** [comment]
post-merge warning added to build:
```
   Compiling posixutils-text v0.2.1 (/Users/jgarzik/repo/posixutils-rs/text)
warning: variant `Unchanged` is never constructed
  --> text/diff_util/change.rs:17:5
   |
14 | pub enum Change {
   |          ------ variant in this enum
...
17 |     Unchanged(ChangeData),
   |     ^^^^^^^^^
   |
   = note: `Change` has derived impls for the traits `Debug` and `Clone`, but these are intentionally ignored during dead code analysis
   = note: `#[warn(dead_code)]` on by default

warning: `posixutils-text` (bin "diff" test) generated 1 warning
warning: `posixutils-text` (bin "diff") generated 1 warning (1 duplicate)
```

also, increasing the speed of diff _tests_ would be nice; they are the slowest tests in posixutils.

**Comment by gcanat** [comment]
Opened a PR to fix the issue with Change enum.
I dont know why the test speed is slow. It seems to lag on startup, maybe some I/O stuff ? When they start running they are fast: `finished in 0.01s`. 
`tree-tests` is slower: `finished in 3.08s`

**Pull request merged**
