### PR TITLE
[realpath] first implementation

### PR DESCRIPTION
**Pull request by ianmclinden**

### CODE REVIEW

**Comment by jgarzik** [comment]
It looks good as a first pass, and passes CI.

However, it is missing the `-E` and `-e` arguments specified by POSIX.

**Comment by ianmclinden** [comment]
Can implement. Do you have reference for `-E` ? Neither Open Group Base nor any of my mans have that flag

**Comment by jgarzik** [comment]
> Can implement. Do you have reference for `-E` ? Neither Open Group Base nor any of my mans have that flag

I am happy to share the specification privately, but cannot share publicly.

**Comment by ianmclinden** [comment]
Implemented `-e|-E` along with the common `--quiet`. 

Errors are left raw from clap for invalid paths - i.e. `''` arguments return the raw clap error `error: one of the values isn't valid for an argument`

**Pull request merged**
