### PR TITLE
Diff

### PR DESCRIPTION
**Pull request by alirezabeygi803**
Hello @jgarzik 
This branch, at the moment, contains diff utility, if you are not happy with the implementation and integration tests, please let me know to work on them more.

Thanks!

### CODE REVIEW

**Comment by muhammadmnorouzi** [comment]
I am double checking and updating a bit of logic and tests, they are failing and logic is not correct for recursive-unified format.

**Comment by alirezabeygi803** [comment]
I am double-checking tests and the logic and will update the branch with new commits.

**Comment by alirezabeygi803** [comment]
added a generator, and fixed issue with context and unified output formats, due to modification date difference.
also refactored a bit

**Comment by alirezabeygi803** [comment]
This shall pass!
Added f3.txt directory to the proper place with .gitkeep inside,
@jgarzik Sorry for bugging you!

**Comment by jgarzik** [comment]
A number of test failures on Macos 14.5:
```
running 235 tests
test diff_tests::test_diff_edit_script ... ok
test diff_tests::test_diff_default ... ok
test diff_tests::test_diff_counting_eol_spaces ... ok
test diff_tests::test_diff_context1 ... FAILED
test diff_tests::test_diff_context3 ... FAILED
test diff_tests::test_diff_directories ... ok
test diff_tests::test_diff_directories_recursive_forward_edit_script ... ok
test diff_tests::test_diff_context10 ... FAILED
test diff_tests::test_diff_directories_recursive_edit_script ... ok
test diff_tests::test_diff_directories_recursive_context ... FAILED
test diff_tests::test_diff_directories_recursive ... ok
test diff_tests::test_diff_directories_recursive_unified ... FAILED
test diff_tests::test_diff_file_directory ... ok
test diff_tests::test_diff_forward_edit_script ... ok
test diff_tests::test_diff_ignoring_eol_spaces ... ok
test diff_tests::test_diff_unified10 ... FAILED
test diff_tests::test_diff_unified3 ... FAILED
test diff_tests::test_diff_unified0 ... FAILED
test diff_tests::test_diff_unified_two_labels ... ok
test sort_tests::test_03a ... ok
test sort_tests::test_02b ... ok
test sort_tests::test_02a ... ok
test sort_tests::test_02m ... ok
test sort_tests::test_02e ... ok
test sort_tests::test_02p ... ok
test sort_tests::test_02d ... ok
test sort_tests::test_02c ... ok
test sort_tests::test_02o ... ok
test sort_tests::test_03b ... ok
test sort_tests::test_03c ... ok
test sort_tests::test_02n ... ok
test sort_tests::test_04a ... ok
test sort_tests::test_03d ... ok
test sort_tests::test_04b ... ok
test sort_tests::test_04c ... ok
test sort_tests::test_04e ... ok
test sort_tests::test_04d ... ok
test sort_tests::test_05a ... ok
test sort_tests::test_05b ... ok
test sort_tests::test_05c ... ok
test sort_tests::test_05d ... ok
test sort_tests::test_05e ... ok
test sort_tests::test_05f ... ok
test sort_tests::test_07a ... ok
test sort_tests::test_07b ... ok
test sort_tests::test_07c ... ok
test sort_tests::test_07e ... ok
test sort_tests::test_08a ... ok
test sort_tests::test_07f ... ok
test sort_tests::test_08b ... ok
test sort_tests::test_09b ... ok
test sort_tests::test_09c ... ok
test sort_tests::test_10a ... ok
test sort_tests::test_10a0 ... ok
test sort_tests::test_10a1 ... ok
test sort_tests::test_10a2 ... ok
test sort_tests::test_10c ... ok
test sort_tests::test_10e ... ok
test sort_tests::test_11a ... ok
test sort_tests::test_11b ... ok
test sort_tests::test_11c ... ok
test sort_tests::test_11d ... ok
test sort_tests::test_14a ... ok
test sort_tests::test_14b ... ok
test sort_tests::test_15a ... ok
test sort_tests::test_15b ... ok
test sort_tests::test_15c ... ok
test sort_tests::test_15d ... ok
test sort_tests::test_15e ... ok
test sort_tests::test_18a ... ok
test sort_tests::test_18b ... ok
test sort_tests::test_18c ... ok
test sort_tests::test_18d ... ok
test sort_tests::test_18e ... ok
test sort_tests::test_18f ... ok
test sort_tests::test_19b ... ok
test sort_tests::test_20a ... ok
test sort_tests::test_21a ... ok
test sort_tests::test_21b ... ok
test sort_tests::test_21c ... ok
test sort_tests::test_21d ... ok
test sort_tests::test_21e ... ok
test sort_tests::test_21g ... ok
test sort_tests::test_22a ... ok
test sort_tests::test_files_sort_1 ... ok
test sort_tests::test_n1 ... ok
test sort_tests::test_files_sort_2 ... ok
test sort_tests::test_n10a ... ok
test sort_tests::test_n10b ... ok
test sort_tests::test_n11a ... ok
test sort_tests::test_n11b ... ok
test sort_tests::test_n2 ... ok
test sort_tests::test_n3 ... ok
test sort_tests::test_n4 ... ok
test sort_tests::test_n5 ... ok
test sort_tests::test_n6 ... ok
test sort_tests::test_n7 ... ok
test sort_tests::test_n8a ... ok
test sort_tests::test_n8b ... ok
test sort_tests::test_n9a ... ok
test sort_tests::test_n9b ... ok
test sort_tests::test_nul_nls ... ok
test sort_tests::test_neg_nls ... ok
test sort_tests::test_use_nl ... ok
test test_csplit_regex_by_empty_lines ... ok
test test_csplit_regex_would_infloop ... ok
test test_csplit_regex_in_seq ... ok
test test_csplit_regex_in_uniq_2 ... ok
test test_csplit_text_by_lines_from_file ... ok
test test_csplit_regex_in_uniq_3 ... ok
test test_csplit_regex_in_uniq ... ok
test test_csplit_text_by_lines ... ok
test test_csplit_c_code_by_regex_suppress ... ok
test test_csplit_c_code_by_regex ... ok
test test_csplit_c_code_by_regex_with_number ... ok
test test_csplit_c_code_by_regex_negative_offset ... ok
test test_expand_basic ... ok
test test_head_basic ... ok
test test_nl_newlines_at_end ... ok
test test_nl_starting_number ... ok
test test_nl_regex ... ok
test test_nl_delimiter ... ok
test test_nl_justification ... ok
test test_nl_number_increment ... ok
test test_pr_expand_and_replace ... ok
test test_pr_limit_lines_trim ... ok
test test_pr_header_replacement ... ok
test test_pr_limit_lines ... ok
test test_pr_offset ... ok
test test_pr_omit_header ... ok
test test_pr_multi_column ... ok
test test_pr_number_line ... ok
test test_pr_multi_column_across ... ok
test test_pr_single_column ... ok
test test_pr_page_skip ... ok
test test_pr_multi_column_merge ... ok
test test_pr_width ... ok
test test_wc_two ... ok
test test_wc_empty ... ok
test test_wc_one ... ok
test tests::test_cut_6 ... ok
test tests::test_cut_b ... ok
test tests::test_cut_5 ... ok
test tests::test_cut_8 ... ok
test tests::test_cut_1 ... ok
test tests::test_cut_9 ... ok
test tests::test_cut_0 ... ok
test tests::test_cut_3 ... ok
test tests::test_cut_4 ... ok
test tests::test_cut_2 ... ok
test tests::test_cut_7 ... ok
test tests::test_cut_a ... ok
test tests::test_cut_f ... ok
test tests::test_cut_c ... ok
test tests::test_cut_l ... ok
test tests::test_cut_k ... ok
test tests::test_cut_j ... ok
test tests::test_cut_i ... ok
test tests::test_cut_e ... ok
test tests::test_cut_h ... ok
test tests::test_cut_m ... ok
test tests::test_cut_n ... ok
test tests::test_cut_newline_1 ... ok
test tests::test_cut_newline_12 ... ok
test tests::test_cut_newline_10 ... ok
test tests::test_cut_newline_13 ... ok
test tests::test_cut_newline_11 ... ok
test tests::test_cut_newline_2 ... ok
test tests::test_cut_newline_14 ... ok
test tests::test_cut_newline_3 ... ok
test tests::test_cut_newline_4 ... ok
test tests::test_cut_newline_5 ... ok
test tests::test_cut_newline_6 ... ok
test tests::test_cut_newline_7 ... ok
test tests::test_cut_newline_8 ... ok
test tests::test_cut_o ... ok
test tests::test_cut_newline_9 ... ok
test tests::test_cut_p ... ok
test tests::test_cut_r ... ok
test tests::test_cut_q ... ok
test tests::test_cut_s ... ok
test tests::test_cut_t ... ok
test tests::test_cut_u ... ok
test tests::test_cut_v ... ok
test tests::test_cut_w ... ok
test tests::test_cut_x ... ok
test tests::test_od_overlap ... ok
test tests::test_od_abut ... ok
test tests::test_od_overlap2 ... ok
test tests::test_od_overlap3 ... ok
test tests::test_od_overlap4 ... ok
test tests::test_od_overlap5 ... ok
test tests::test_out_delim_1 ... ok
test tests::test_out_delim_2 ... ok
test tests::test_out_delim_3 ... ok
test tests::test_out_delim_3a ... ok
test tests::test_out_delim_4 ... ok
test tests::test_out_delim_5 ... ok
test tests::test_out_delim_6 ... ok
test uniq_tests::test_uniq_13 ... ok
test uniq_tests::test_uniq_11 ... ok
test uniq_tests::test_uniq_25 ... ok
test uniq_tests::test_uniq_2 ... ok
test uniq_tests::test_uniq_23 ... ok
test uniq_tests::test_uniq_22 ... ok
test uniq_tests::test_uniq_21 ... ok
test uniq_tests::test_uniq_12 ... ok
test uniq_tests::test_uniq_20 ... ok
test uniq_tests::test_uniq_24 ... ok
test uniq_tests::test_uniq_10 ... ok
test uniq_tests::test_uniq_26 ... ok
test uniq_tests::test_uniq_28 ... ok
test uniq_tests::test_uniq_27 ... ok
test uniq_tests::test_uniq_29 ... ok
test uniq_tests::test_uniq_3 ... ok
test uniq_tests::test_uniq_30 ... ok
test uniq_tests::test_uniq_31 ... ok
test uniq_tests::test_uniq_32 ... ok
test uniq_tests::test_uniq_33 ... ok
test uniq_tests::test_uniq_34 ... ok
test uniq_tests::test_uniq_35 ... ok
test uniq_tests::test_uniq_36 ... ok
test uniq_tests::test_uniq_37 ... ok
test uniq_tests::test_uniq_38 ... ok
test uniq_tests::test_uniq_39 ... ok
test uniq_tests::test_uniq_4 ... ok
test uniq_tests::test_uniq_40 ... ok
test uniq_tests::test_uniq_41 ... ok
test uniq_tests::test_uniq_42 ... ok
test uniq_tests::test_uniq_43 ... ok
test uniq_tests::test_uniq_6 ... ok
test uniq_tests::test_uniq_5 ... ok
test uniq_tests::test_uniq_7 ... ok
test uniq_tests::test_uniq_8 ... ok
test uniq_tests::test_uniq_9 ... ok

failures:

---- diff_tests::test_diff_context1 stdout ----
thread 'diff_tests::test_diff_context1' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "*** tests/diff/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n--- tests/diff/f2.txt\tFri, 24 May 2024 09:38:46 -0400\n***************\n*** 5,14 ***\n  line 5\n! line 6 will change\n  line 7\n  \n- This line will be removed\n- \n  line 8\n! line 9 will change\n! line 10 will change\n  \n--- 5,12 ---\n  line 5\n! line 6 is updated\n  line 7\n- \n  line 8\n! line 9 is updated\n! line 10 is updated\n  \n**************\n*** 16,17 ***\n  \n- This will be removed, too\n--- 13,13 ---\n"
 right: "*** tests/diff/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n--- tests/diff/f2.txt\tFri, 24 May 2024 13:38:46 +0000\n***************\n*** 5,14 ***\n  line 5\n! line 6 will change\n  line 7\n  \n- This line will be removed\n- \n  line 8\n! line 9 will change\n! line 10 will change\n  \n--- 5,12 ---\n  line 5\n! line 6 is updated\n  line 7\n- \n  line 8\n! line 9 is updated\n! line 10 is updated\n  \n**************\n*** 16,17 ***\n  \n- This will be removed, too\n--- 13,13 ---\n"
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- diff_tests::test_diff_context3 stdout ----
thread 'diff_tests::test_diff_context3' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "*** tests/diff/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n--- tests/diff/f2.txt\tFri, 24 May 2024 09:38:46 -0400\n***************\n*** 3,17 ***\n  \n  line 4\n  line 5\n! line 6 will change\n  line 7\n  \n- This line will be removed\n- \n  line 8\n! line 9 will change\n! line 10 will change\n  \n  line 11\n  \n- This will be removed, too\n--- 3,13 ---\n  \n  line 4\n  line 5\n! line 6 is updated\n  line 7\n- \n  line 8\n! line 9 is updated\n! line 10 is updated\n  \n  line 11\n"
 right: "*** tests/diff/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n--- tests/diff/f2.txt\tFri, 24 May 2024 13:38:46 +0000\n***************\n*** 3,17 ***\n  \n  line 4\n  line 5\n! line 6 will change\n  line 7\n  \n- This line will be removed\n- \n  line 8\n! line 9 will change\n! line 10 will change\n  \n  line 11\n  \n- This will be removed, too\n--- 3,13 ---\n  \n  line 4\n  line 5\n! line 6 is updated\n  line 7\n- \n  line 8\n! line 9 is updated\n! line 10 is updated\n  \n  line 11\n"

---- diff_tests::test_diff_context10 stdout ----
thread 'diff_tests::test_diff_context10' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "*** tests/diff/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n--- tests/diff/f2.txt\tFri, 24 May 2024 09:38:46 -0400\n***************\n*** 1,17 ***\n  line 1\n  line 2\n  \n  line 4\n  line 5\n! line 6 will change\n  line 7\n  \n- This line will be removed\n- \n  line 8\n! line 9 will change\n! line 10 will change\n  \n  line 11\n  \n- This will be removed, too\n--- 1,13 ---\n  line 1\n  line 2\n  \n  line 4\n  line 5\n! line 6 is updated\n  line 7\n- \n  line 8\n! line 9 is updated\n! line 10 is updated\n  \n  line 11\n"
 right: "*** tests/diff/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n--- tests/diff/f2.txt\tFri, 24 May 2024 13:38:46 +0000\n***************\n*** 1,17 ***\n  line 1\n  line 2\n  \n  line 4\n  line 5\n! line 6 will change\n  line 7\n  \n- This line will be removed\n- \n  line 8\n! line 9 will change\n! line 10 will change\n  \n  line 11\n  \n- This will be removed, too\n--- 1,13 ---\n  line 1\n  line 2\n  \n  line 4\n  line 5\n! line 6 is updated\n  line 7\n- \n  line 8\n! line 9 is updated\n! line 10 is updated\n  \n  line 11\n"

---- diff_tests::test_diff_directories_recursive_context stdout ----
thread 'diff_tests::test_diff_directories_recursive_context' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "*** tests/diff/f1/empty/f1.txt\tSat, 25 May 2024 03:04:10 -0400\n--- tests/diff/f2/empty/f1.txt\tSat, 25 May 2024 03:04:10 -0400\ndiff -C 3 -r tests/diff/f1/f1.txt tests/diff/f2/f1.txt \n*** tests/diff/f1/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n--- tests/diff/f2/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n***************\n*** 3,17 ***\n  \n  line 4\n  line 5\n! line 6 will change\n  line 7\n  \n- This line will be removed\n- \n  line 8\n! line 9 will change\n! line 10 will change\n  \n  line 11\n  \n- This will be removed, too\n--- 3,13 ---\n  \n  line 4\n  line 5\n! line 6 is updated\n  line 7\n- \n  line 8\n! line 9 is updated\n! line 10 is updated\n  \n  line 11\nFile \"tests/diff/f1/f3.txt\" is a directory while file \"tests/diff/f2/f3.txt\" is a regular file\n"
 right: "*** tests/diff/f1/empty/f1.txt\tSat, 25 May 2024 07:04:10 +0000\n--- tests/diff/f2/empty/f1.txt\tSat, 25 May 2024 07:04:10 +0000\ndiff -C 3 -r tests/diff/f1/f1.txt tests/diff/f2/f1.txt \n*** tests/diff/f1/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n--- tests/diff/f2/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n***************\n*** 3,17 ***\n  \n  line 4\n  line 5\n! line 6 will change\n  line 7\n  \n- This line will be removed\n- \n  line 8\n! line 9 will change\n! line 10 will change\n  \n  line 11\n  \n- This will be removed, too\n--- 3,13 ---\n  \n  line 4\n  line 5\n! line 6 is updated\n  line 7\n- \n  line 8\n! line 9 is updated\n! line 10 is updated\n  \n  line 11\nFile \"tests/diff/f1/f3.txt\" is a directory while file \"tests/diff/f2/f3.txt\" is a regular file\n"

---- diff_tests::test_diff_directories_recursive_unified stdout ----
thread 'diff_tests::test_diff_directories_recursive_unified' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "--- tests/diff/f1/empty/f1.txt\tSat, 25 May 2024 03:04:10 -0400\n+++ tests/diff/f2/empty/f1.txt\tSat, 25 May 2024 03:04:10 -0400\ndiff -U 3 -r tests/diff/f1/f1.txt tests/diff/f2/f1.txt \n--- tests/diff/f1/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n+++ tests/diff/f2/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n@@ -3,15 +3,11 @@\n \n line 4\n line 5\n-line 6 will change\n+line 6 is updated\n line 7\n \n-This line will be removed\n-\n \n line 8\n-line 9 will change\n+line 9 is updated\n-line 10 will change\n+line 10 is updated\n \n line 11\n-This will be removed, too\nFile \"tests/diff/f1/f3.txt\" is a directory while file \"tests/diff/f2/f3.txt\" is a regular file\n"
 right: "--- tests/diff/f1/empty/f1.txt\tSat, 25 May 2024 07:04:10 +0000\n+++ tests/diff/f2/empty/f1.txt\tSat, 25 May 2024 07:04:10 +0000\ndiff -U 3 -r tests/diff/f1/f1.txt tests/diff/f2/f1.txt \n--- tests/diff/f1/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n+++ tests/diff/f2/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n@@ -3,15 +3,11 @@\n \n line 4\n line 5\n-line 6 will change\n+line 6 is updated\n line 7\n \n-This line will be removed\n-\n \n line 8\n-line 9 will change\n+line 9 is updated\n-line 10 will change\n+line 10 is updated\n \n line 11\n-This will be removed, too\nFile \"tests/diff/f1/f3.txt\" is a directory while file \"tests/diff/f2/f3.txt\" is a regular file\n"

---- diff_tests::test_diff_unified10 stdout ----
thread 'diff_tests::test_diff_unified10' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "--- tests/diff/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n+++ tests/diff/f2.txt\tFri, 24 May 2024 09:38:46 -0400\n@@ -1,17 +1,13 @@\n line 1\n line 2\n \n line 4\n line 5\n-line 6 will change\n+line 6 is updated\n line 7\n \n-This line will be removed\n-\n \n line 8\n-line 9 will change\n+line 9 is updated\n-line 10 will change\n+line 10 is updated\n \n line 11\n-This will be removed, too\n"
 right: "--- tests/diff/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n+++ tests/diff/f2.txt\tFri, 24 May 2024 13:38:46 +0000\n@@ -1,17 +1,13 @@\n line 1\n line 2\n \n line 4\n line 5\n-line 6 will change\n+line 6 is updated\n line 7\n \n-This line will be removed\n-\n \n line 8\n-line 9 will change\n+line 9 is updated\n-line 10 will change\n+line 10 is updated\n \n line 11\n-This will be removed, too\n"

---- diff_tests::test_diff_unified3 stdout ----
thread 'diff_tests::test_diff_unified3' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "--- tests/diff/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n+++ tests/diff/f2.txt\tFri, 24 May 2024 09:38:46 -0400\n@@ -3,15 +3,11 @@\n \n line 4\n line 5\n-line 6 will change\n+line 6 is updated\n line 7\n \n-This line will be removed\n-\n \n line 8\n-line 9 will change\n+line 9 is updated\n-line 10 will change\n+line 10 is updated\n \n line 11\n-This will be removed, too\n"
 right: "--- tests/diff/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n+++ tests/diff/f2.txt\tFri, 24 May 2024 13:38:46 +0000\n@@ -3,15 +3,11 @@\n \n line 4\n line 5\n-line 6 will change\n+line 6 is updated\n line 7\n \n-This line will be removed\n-\n \n line 8\n-line 9 will change\n+line 9 is updated\n-line 10 will change\n+line 10 is updated\n \n line 11\n-This will be removed, too\n"

---- diff_tests::test_diff_unified0 stdout ----
thread 'diff_tests::test_diff_unified0' panicked at plib/src/testing.rs:52:5:
assertion `left == right` failed
  left: "--- tests/diff/f1.txt\tFri, 24 May 2024 09:38:46 -0400\n+++ tests/diff/f2.txt\tFri, 24 May 2024 09:38:46 -0400\n@@ -6 +6 @@\n-line 6 will change\n+line 6 is updated\n@@ -9,2 +8,0 @@\n-This line will be removed\n-\n@@ -12,2 +10,2 @@\n-line 9 will change\n+line 9 is updated\n-line 10 will change\n+line 10 is updated\n@@ -17 +13 @@\n line 11\n-This will be removed, too\n"
 right: "--- tests/diff/f1.txt\tFri, 24 May 2024 13:38:46 +0000\n+++ tests/diff/f2.txt\tFri, 24 May 2024 13:38:46 +0000\n@@ -6 +6 @@\n-line 6 will change\n+line 6 is updated\n@@ -9,2 +8,0 @@\n-This line will be removed\n-\n@@ -12,2 +10,2 @@\n-line 9 will change\n+line 9 is updated\n-line 10 will change\n+line 10 is updated\n@@ -17 +13 @@\n line 11\n-This will be removed, too\n"


failures:
    diff_tests::test_diff_context1
    diff_tests::test_diff_context10
    diff_tests::test_diff_context3
    diff_tests::test_diff_directories_recursive_context
    diff_tests::test_diff_directories_recursive_unified
    diff_tests::test_diff_unified0
    diff_tests::test_diff_unified10
    diff_tests::test_diff_unified3

test result: FAILED. 227 passed; 8 failed; 0 ignored; 0 measured; 0 filtered out; finished in 1.51s

error: test failed, to rerun pass `-p posixutils-text --test integration`

```

**Comment by alirezabeygi803** [comment]
generating all test artifacts right before running tests, in each OS, so it will fix any problems related to time-zone and dates

**Comment by jgarzik** [comment]
**It feels like we are very close!**   It is passing all my local tests (macos, linux) and passing all CI (macos, linux).  All good progress there.

However, it is not a good outcome to modify checked-in files:
```
On branch diff-merge
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   Cargo.lock
	modified:   text/tests/diff/context_10_output.txt
	modified:   text/tests/diff/context_1_output.txt
	modified:   text/tests/diff/context_output.txt
	modified:   text/tests/diff/f1_f2_recursive_context_output.txt
	modified:   text/tests/diff/f1_f2_recursive_unified_output.txt
	modified:   text/tests/diff/unified_0_output.txt
	modified:   text/tests/diff/unified_10_output.txt
	modified:   text/tests/diff/unified_output.txt

```

Need to find another test solution that passes the `git status` test (no modified files, from git point of view).

**Comment by alirezabeygi803** [comment]
Added diff test artifacts to .gitignore, so testing won't cause git status show modified files.

**Comment by jgarzik** [comment]
heh.  We cannot simply ignore the test output :).  The normal standard is to be "clean":  if files are created by a test, then delete those files at the end of the test.

The build tree needs to behave predictably, which means cleaning up after tests.  The files are still there:
```
% git clean -dfx
Removing target/
Removing text/tests/diff/context_10_output.txt
Removing text/tests/diff/context_1_output.txt
Removing text/tests/diff/context_output.txt
Removing text/tests/diff/default_output.txt
Removing text/tests/diff/edit_script_output.txt
Removing text/tests/diff/f1_counting_eol_spacesd_output.txt
Removing text/tests/diff/f1_f2_default_output.txt
Removing text/tests/diff/f1_f2_recursive_context_output.txt
Removing text/tests/diff/f1_f2_recursive_ed_output.txt
Removing text/tests/diff/f1_f2_recursive_f_output.txt
Removing text/tests/diff/f1_f2_recursive_output.txt
Removing text/tests/diff/f1_f2_recursive_unified_output.txt
Removing text/tests/diff/f1_ignoring_eol_spacesd_output.txt
Removing text/tests/diff/file_dir_output.txt
Removing text/tests/diff/forward_edit_script_output.txt
Removing text/tests/diff/label_output.txt
Removing text/tests/diff/unified_0_output.txt
Removing text/tests/diff/unified_10_output.txt
Removing text/tests/diff/unified_output.txt
```

This git repository needs to behave similarly to the overwhelming majority of github repositories ("Principle of Least Surprise").  That means tests should clean up after themselves.  Can you not put this stuff into cargo tmp (./target/tmp)?  Take a look at the cp/mv/rm tests for example.

**Comment by alirezabeygi803** [comment]
OK, before and after testing will look the same, without any file/directory ignorance.
Thanks for your patience.

**Comment by alirezabeygi803** [comment]
Let's reduce IO, refactored integration tests for diff in a way, so any scenarios can be implemented easier and faster.
At the moment, I am running the expected diff command, then capture it's output on the fly and then doing the test, 
If this is not what it should be, so please exactly let me know the details to work on.

This new refactored code is easier to maintain and change.
Thanks!

**Comment by jgarzik** [comment]
I think the testing is now looking good -- works for me locally -- looks like CI macos is still unhappy.

Very, very, very close to merge ready - just need to fix CI

**Comment by alirezabeygi803** [comment]
I am wondering what the issue source is, it seems one of the child processes, randomly failed to be created, while they were independent, what is your opinion about the solution to this problem, as it is hard to recreate it?

**Pull request merged**
