### PR TITLE
Improve wc

### PR DESCRIPTION
**Pull request by gcanat**
As suggested in #137, I took inspiration from [wc2](https://github.com/robertdavidgraham/wc2) to improve wc_file_bytes.

In my benchmarks (tested with 1G utf8.txt file generated with [wctool](https://github.com/robertdavidgraham/wc2/blob/master/wctool.c)), it is a bit faster than wc2, and on par with [wz](https://github.com/Altair-Bueno/wz), except when passing multiple files as argument because wz will parallelize computation, but I guess we don't want to pull rayon as a dependency here :)

### CODE REVIEW

**Comment by jgarzik** [comment]
Looks good at a quick glance.

The table initialization can be improved further with a static table, yes?   e.g. https://www.reddit.com/r/rust/comments/1dokkh2/recipe_for_compiletime_sparse_array_initialization/

**Comment by gcanat** [comment]
OK I made the change.
For what it's worth here's the result on 1G utf8.txt

| tool               | branch | time  |
| ----------------- | ---------  | -------- |
|posixutils-rs | main    | 2.66s  |
|posixutils-rs | wc2      | 1.50s  |
|wc2.c             | main    | 2.10s  |
| wz                 | main    | 1.57s  |
| wc                 | v8.32   |  15.33 |

**Comment by jgarzik** [comment]
Thanks, merged.

Interested in tackling wc_file_chars()?  :)

**Comment by jgarzik** [comment]
Post-merge comment:  `was_space` need not appear in `CountInfo` at all, as far as I can tell.

**Comment by gcanat** [comment]
Oh yeah, I can have a look at `wc_file_chars()` in the coming days. And will try to handle `was_space` differently.

**Pull request merged**
