### PR TITLE
Make changes needed to build on musl

### PR DESCRIPTION
**Pull request by andrewliebenow**
Also: move some platform-specific code into plib.

### CODE REVIEW

**Comment by jgarzik** [comment]
Looks pretty good, and close.

Nits:
- linux CI failing
- prefer to name plib ipc module `ipc.rs` not `sys.rs`

**Comment by andrewliebenow** [comment]
I suspect that tests in which the program does some processing and then later starts reading from stdin to get user confirmation are subject to intermittent failure like happened here.

```
    let mut child = command
        .args(args)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("failed to spawn head");

    let stdin = child.stdin.as_mut().expect("failed to get stdin");
    stdin
        .write_all(stdin_data)
        .expect("failed to write to stdin");
```

In order to make these tests totally reliable, there would probably need to be some logic to only start writing to stdin after the program writes something to stdout indicating that it's waiting on user input. Not sure it's worth doing that vs. just putting up with random test failures.

**Comment by jgarzik** [comment]
Yes, after pounding on the "re-run failed tests" a few times, skipping `grep` test inconsistencies, the checks eventually pass.

This PR is looking pretty good.  Will give it another review post-travel (~Saturday), and probably merge.

As a more general comment, it is preferred to separate out commits into logical changes, for example in this PR,  something like
C1:  create and use platform module
C2: create and use plib/terminal
C3: create and use plib/priority
C4: add support for musl

See this doc from my old Linux kernel buddy for more examples: https://github.com/axboe/liburing/blob/master/CONTRIBUTING.md

**Comment by jgarzik** [comment]
Cherry-picked some of the changes - with slight modification - whittling this core PR down a bit.

**Comment by jgarzik** [comment]
With #232, I _think_ all of this is merged (inclusive of my own modifications).

ipcs/ipcrm could probably use some considered attention for macos and linux as well as musl.  I am hopeful that a good strategy would emerge.

**Comment by andrewliebenow** [comment]
Awesome, thanks for getting this in.

**Pull request closed without merging**
