### PR TITLE
Make changes needed to build on musl

### PR DESCRIPTION
**Pull request by andrewliebenow**

### CODE REVIEW

**Comment by andrewliebenow** [comment]
I only checked that the project builds on "x86_64-unknown-linux-musl". This is pretty ugly, but maybe someone will want to use this as a starting point re: musl support.

**Comment by jgarzik** [comment]
Neat!   I'll think a bit about the best way to merge this, specifically `libc_aliases`

Initial reaction:   This PR serves to highlight the need to isolate libc functions in plib crate, and remove any need to touch individual utils with `libc_aliases` related changes directly.

**Comment by andrewliebenow** [comment]
👍🏻. Some of the hacky special casing for musl will be unnecessary when https://github.com/rust-lang/libc/issues/3190 is resolved, so one option would be to just wait on that. I made a PR to add some missing constants (https://github.com/rust-lang/libc/pull/3908), but I would assume it's not easy/quick to get things merged into the `libc` crate.

**Comment by jgarzik** [comment]
High level guidance thoughts:

- We **do** want to support platforms such as musl
- Having unsafe libc calls in utils is distasteful...  unwanted but sometimes necessary.
- Adding conditional compilation to utils due to this only compounds the uglyliness
- The proper solution is to have a plib (posixutils' internal library crate) or another crate provide a nice, clean, safe wrapper for the _class_ of libc library function.
- restrict musl ifdefs to plib, unless there is an incredibly strong reason (c.f. getconf)

**Comment by jgarzik** [comment]
On-going comments:
* The `platform:XXX` direction is good.  This removes libc references from non-plib code; an improvement.
* Dislike `PPriorityWhichT` -- it is better to promote `xgetpriority` and `xsetpriority` to a new plib/priority.rs module, remove the 'x' prefix, and bury all the glibc/musl/macos ifdefs in plib/priority.rs.  Making the cast portable just extends the ugliness, which we would rather leave renice.rs altogether.
* Happy to entertain cleanups, as separate PRs, to keep this PR smaller and self-contained.

**Comment by andrewliebenow** [comment]
Closed in favor of https://github.com/rustcoreutils/posixutils-rs/pull/198

**Pull request closed without merging**
