### PR TITLE
Add secondary platforms workflow

### PR DESCRIPTION
**Pull request by andrewliebenow**

### CODE REVIEW

**Comment by andrewliebenow** [comment]
I don't know why some fuser tests are failing on `arch64-unknown-linux-gnu`.

@Wandalen

**Comment by andrewliebenow** [comment]
Never mind, I set something up wrong.

Note that this PR does not actually run the tests on these other platforms, it just checks that the project compiles.

**Comment by jgarzik** [comment]
> I don't know why some fuser tests are failing on `arch64-unknown-linux-gnu`.
> 
> @Wandalen

"fuser is the new grep".  Unfortunately, having solved the grep test issues, fuser now intermittently fails in its udp or tcp tests.

**Comment by jgarzik** [comment]
> Never mind, I set something up wrong.

OK.

As a general comment, it is preferred to add new platform CIs after someone gets the posixutils working on that platform with no exclusions.

**Pull request closed without merging**
