### PR TITLE
Move plib to [dev-dependencies]

### PR DESCRIPTION
**Pull request by fox0**

### CODE REVIEW

**Comment by jgarzik** [comment]
This appears to be a regression:  Changing a simple compile-time constant to reading a runtime environment variable into a program variable.  This is less optimal and more compiled output for no apparent value?

**Comment by fox0** [comment]
It is compile time: https://doc.rust-lang.org/std/macro.env.html

**Comment by fox0** [comment]
```
$ cargo expand --bin sleep main
   Compiling proc-macro2 v1.0.86
   Compiling libc v0.2.159
   Compiling num-traits v0.2.19
   Compiling quote v1.0.37
    Checking chrono v0.4.38
   Compiling syn v2.0.79
   Compiling clap_derive v4.5.18
    Checking clap v4.5.18
    Checking posixutils-datetime v0.2.1 (/home/fox/just_for_fun/posixutils-rs/datetime)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 4.36s

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let args = Args::parse();
    setlocale(LocaleCategory::LcAll, "");
    textdomain("posixutils-rs")?;
    bind_textdomain_codeset("posixutils-rs", "UTF-8")?;
    unsafe {
        signal(SIGALRM, SIG_IGN);
    }
    thread::sleep(time::Duration::from_secs(args.seconds));
    Ok(())
}
```

**Comment by jgarzik** [comment]
maybe later. too big, for the moment.

**Pull request closed without merging**
